import { RoadSegment, SchoolBus, PublicTransportRoute, FreightShift, OptimizationPillar } from './types';

export const MOCK_ROADS: RoadSegment[] = [
  {
    id: 'road-hinjawadi',
    name: 'Hinjawadi IT Park Flyover & Wakad Arterial',
    code: 'HIN-01',
    zone: 'Hinjawadi Infotech Zone (Phase 1-3)',
    lengthKm: 7.2,
    freeFlowSpeedKmh: 50,
    normalSpeed: 50,
    speed: 12,
    currentSpeedKmh: 12,
    flow: 3850,
    baselineVolume: 3850,
    optimizedVolume: 2350,
    capacity: 3200,
    capacityVehHr: 3200,
    utilization: 96,
    status: 'critical',
    pathData: 'M 120 180 Q 260 220 420 280 T 600 310 T 780 350',
    centerPoint: { x: 420, y: 280 },
    coordinates: [
      { x: 120, y: 180 },
      { x: 260, y: 220 },
      { x: 420, y: 280 },
      { x: 600, y: 310 },
      { x: 780, y: 350 },
    ],
    schoolBusCount: 38,
    freightCount: 126,
    publicBusCount: 42,
    delayMinutes: 26,
    vehicleDistribution: {
      cars: 46,
      publicTransport: 16,
      schoolBuses: 24,
      freight: 14,
      twoWheelers: 32,
    },
    prediction: [
      { time: '06:30', speed: 38, congestion: 35, flow: 1200, utilization: 35 },
      { time: '06:45', speed: 30, congestion: 54, flow: 1750, utilization: 54 },
      { time: '07:00', speed: 22, congestion: 74, flow: 2400, utilization: 74 },
      { time: '07:15', speed: 16, congestion: 90, flow: 2900, utilization: 90 },
      { time: '07:30', speed: 12, congestion: 96, flow: 3100, utilization: 96 },
      { time: '07:45', speed: 9, congestion: 99, flow: 3250, utilization: 99 },
      { time: '08:00', speed: 14, congestion: 88, flow: 2850, utilization: 88 },
    ],
    bottleneckDescription: 'Wakad bridge bottleneck and Hinjawadi Phase 1 junction tech commuter surge.',
    criticalHour: '07:15 - 08:45 AM',
    rerouteOptions: [
      { name: 'Baner-Balewadi Alternate Bypass', capacityAvailablePct: 52, delayAddedMin: 3.2 },
      { name: 'Maan-Mahalunge Smart Link Road', capacityAvailablePct: 38, delayAddedMin: 4.8 },
    ],
  },
  {
    id: 'road-baner',
    name: 'Baner-Balewadi Alternate Bypass',
    code: 'BAN-02',
    zone: 'West Pune Suburban Arterial',
    lengthKm: 8.5,
    freeFlowSpeedKmh: 55,
    normalSpeed: 55,
    speed: 38,
    currentSpeedKmh: 38,
    flow: 1200,
    baselineVolume: 1200,
    optimizedVolume: 2250,
    capacity: 3400,
    capacityVehHr: 3400,
    utilization: 35,
    status: 'low',
    pathData: 'M 120 300 Q 280 360 480 410 T 680 430 T 820 460',
    centerPoint: { x: 480, y: 410 },
    coordinates: [
      { x: 120, y: 300 },
      { x: 280, y: 360 },
      { x: 480, y: 410 },
      { x: 680, y: 430 },
      { x: 820, y: 460 },
    ],
    schoolBusCount: 8,
    freightCount: 22,
    publicBusCount: 16,
    delayMinutes: 3,
    vehicleDistribution: {
      cars: 40,
      publicTransport: 20,
      schoolBuses: 15,
      freight: 25,
      twoWheelers: 35,
    },
    prediction: [
      { time: '06:30', speed: 50, congestion: 18, flow: 600, utilization: 18 },
      { time: '06:45', speed: 46, congestion: 24, flow: 800, utilization: 24 },
      { time: '07:00', speed: 43, congestion: 28, flow: 950, utilization: 28 },
      { time: '07:15', speed: 40, congestion: 32, flow: 1100, utilization: 32 },
      { time: '07:30', speed: 38, congestion: 35, flow: 1200, utilization: 35 },
      { time: '07:45', speed: 36, congestion: 39, flow: 1320, utilization: 39 },
      { time: '08:00', speed: 40, congestion: 32, flow: 1080, utilization: 32 },
    ],
    bottleneckDescription: 'Underutilized 6-lane arterial bypass corridor ideal for absorbing diverted traffic.',
    criticalHour: '07:30 - 08:30 AM',
  },
  {
    id: 'road-shivajinagar',
    name: 'Shivaji Nagar (JM Road / FC Road Corridor)',
    code: 'SJN-03',
    zone: 'Central Commercial & Educational Hub',
    lengthKm: 6.4,
    freeFlowSpeedKmh: 45,
    normalSpeed: 45,
    speed: 16,
    currentSpeedKmh: 16,
    flow: 2900,
    baselineVolume: 3500,
    optimizedVolume: 2750,
    capacity: 3500,
    capacityVehHr: 3500,
    utilization: 82,
    status: 'high',
    pathData: 'M 80 450 Q 240 460 440 480 T 650 500 T 860 520',
    centerPoint: { x: 440, y: 480 },
    coordinates: [
      { x: 80, y: 450 },
      { x: 240, y: 460 },
      { x: 440, y: 480 },
      { x: 650, y: 500 },
      { x: 860, y: 520 },
    ],
    schoolBusCount: 24,
    freightCount: 65,
    publicBusCount: 60,
    delayMinutes: 18,
    vehicleDistribution: {
      cars: 48,
      publicTransport: 24,
      schoolBuses: 18,
      freight: 10,
      twoWheelers: 38,
    },
    prediction: [
      { time: '06:30', speed: 38, congestion: 30, flow: 1050, utilization: 30 },
      { time: '06:45', speed: 32, congestion: 48, flow: 1680, utilization: 48 },
      { time: '07:00', speed: 26, congestion: 65, flow: 2275, utilization: 65 },
      { time: '07:15', speed: 20, congestion: 76, flow: 2660, utilization: 76 },
      { time: '07:30', speed: 16, congestion: 82, flow: 2900, utilization: 82 },
      { time: '07:45', speed: 14, congestion: 88, flow: 3100, utilization: 88 },
      { time: '08:00', speed: 17, congestion: 80, flow: 2800, utilization: 80 },
    ],
    bottleneckDescription: 'Sancheti hospital intersection and Modern High School bus arrival friction.',
    criticalHour: '07:30 - 09:15 AM',
  },
  {
    id: 'road-sbroad',
    name: 'Senapati Bapat Road & University Circle',
    code: 'SBR-04',
    zone: 'Institutional & Tech Park Hub',
    lengthKm: 5.8,
    freeFlowSpeedKmh: 45,
    normalSpeed: 45,
    speed: 24,
    currentSpeedKmh: 24,
    flow: 2200,
    baselineVolume: 2900,
    optimizedVolume: 2400,
    capacity: 3200,
    capacityVehHr: 3200,
    utilization: 68,
    status: 'moderate',
    pathData: 'M 620 120 Q 680 220 740 340 T 800 460',
    centerPoint: { x: 740, y: 340 },
    coordinates: [
      { x: 620, y: 120 },
      { x: 680, y: 220 },
      { x: 740, y: 340 },
      { x: 800, y: 460 },
    ],
    schoolBusCount: 18,
    freightCount: 45,
    publicBusCount: 48,
    delayMinutes: 10,
    vehicleDistribution: {
      cars: 48,
      publicTransport: 22,
      schoolBuses: 18,
      freight: 12,
      twoWheelers: 34,
    },
    prediction: [
      { time: '06:30', speed: 44, congestion: 24, flow: 770, utilization: 24 },
      { time: '06:45', speed: 38, congestion: 40, flow: 1280, utilization: 40 },
      { time: '07:00', speed: 32, congestion: 52, flow: 1660, utilization: 52 },
      { time: '07:15', speed: 28, congestion: 60, flow: 1920, utilization: 60 },
      { time: '07:30', speed: 24, congestion: 68, flow: 2200, utilization: 68 },
      { time: '07:45', speed: 21, congestion: 74, flow: 2360, utilization: 74 },
      { time: '08:00', speed: 25, congestion: 64, flow: 2050, utilization: 64 },
    ],
    bottleneckDescription: 'Symbiosis College junction and ICC Tech Park turnoff queue.',
    criticalHour: '07:45 - 09:15 AM',
  },
  {
    id: 'road-swargate',
    name: 'Swargate Hub - Katraj Arterial',
    code: 'SWA-05',
    zone: 'South Pune Mass Transit Terminal',
    lengthKm: 9.8,
    freeFlowSpeedKmh: 50,
    normalSpeed: 50,
    speed: 13,
    currentSpeedKmh: 13,
    flow: 4700,
    baselineVolume: 5400,
    optimizedVolume: 4100,
    capacity: 4800,
    capacityVehHr: 4800,
    utilization: 94,
    status: 'critical',
    pathData: 'M 180 100 Q 240 240 300 380 T 360 520',
    centerPoint: { x: 300, y: 380 },
    coordinates: [
      { x: 180, y: 100 },
      { x: 240, y: 240 },
      { x: 300, y: 380 },
      { x: 360, y: 520 },
    ],
    schoolBusCount: 28,
    freightCount: 160,
    publicBusCount: 88,
    delayMinutes: 27,
    vehicleDistribution: {
      cars: 52,
      publicTransport: 20,
      schoolBuses: 12,
      freight: 16,
      twoWheelers: 26,
    },
    prediction: [
      { time: '06:30', speed: 48, congestion: 32, flow: 1530, utilization: 32 },
      { time: '06:45', speed: 36, congestion: 55, flow: 2640, utilization: 55 },
      { time: '07:00', speed: 25, congestion: 74, flow: 3550, utilization: 74 },
      { time: '07:15', speed: 18, congestion: 86, flow: 4120, utilization: 86 },
      { time: '07:30', speed: 13, congestion: 94, flow: 4700, utilization: 94 },
      { time: '07:45', speed: 10, congestion: 98, flow: 4900, utilization: 98 },
      { time: '08:00', speed: 14, congestion: 90, flow: 4320, utilization: 90 },
    ],
    bottleneckDescription: 'Swargate Flyover merge and Jedhe Chowk multi-arterial crossing.',
    criticalHour: '07:30 - 10:00 AM',
  },
];

export const GREENWOOD_BUS_FLEET: SchoolBus[] = [
  {
    busId: 'PUN-SB01',
    routeName: 'Route 1: Kothrud Hub -> Symbiosis / MIT Campus',
    driverName: 'Santosh Jadhav',
    studentsCount: 44,
    studentCount: 44,
    capacity: 50,
    occupancyRate: 88,
    status: 'Rerouted',
    currentRoute: 'Via Shivaji Nagar JM Road',
    currentDeparture: '06:25 AM',
    currentEta: '07:14 AM (+14m Late)',
    recommendedRoute: 'Via Law College Road Bypass',
    recommendedDeparture: '06:25 AM',
    recommendedEta: '06:58 AM (On-Time)',
    delayAvoidedMin: 14,
    currentCorridor: 'Shivaji Nagar JM Road',
    recommendedCorridor: 'Law College Road Bypass',
  },
  {
    busId: 'PUN-SB02',
    routeName: 'Route 2: Wakad Bridge -> Hinjawadi DPS Campus',
    driverName: 'Rameshwar Shinde',
    studentsCount: 42,
    studentCount: 42,
    capacity: 50,
    occupancyRate: 84,
    status: 'Retimed',
    currentRoute: 'Standard Wakad Flyover Corridor',
    currentDeparture: '06:25 AM',
    currentEta: '07:18 AM (+18m Late)',
    recommendedRoute: 'Early Departure Window (Clear slot)',
    recommendedDeparture: '06:15 AM (-10m)',
    recommendedEta: '06:52 AM (On-Time)',
    delayAvoidedMin: 18,
    currentCorridor: 'Hinjawadi Flyover',
    recommendedCorridor: 'Hinjawadi Flyover (Clear window)',
  },
  {
    busId: 'PUN-SB03',
    routeName: 'Route 3: Hadapsar Magarpatta -> Bishop School Camp',
    driverName: 'Anil Deshmukh',
    studentsCount: 48,
    studentCount: 48,
    capacity: 50,
    occupancyRate: 96,
    status: 'Rerouted',
    currentRoute: 'Via Solapur Road & Fatimanagar',
    currentDeparture: '06:20 AM',
    currentEta: '07:12 AM (+12m Late)',
    recommendedRoute: 'Via Wanowrie Outer Link',
    recommendedDeparture: '06:20 AM',
    recommendedEta: '06:55 AM (On-Time)',
    delayAvoidedMin: 12,
    currentCorridor: 'Solapur Arterial',
    recommendedCorridor: 'Wanowrie Outer Link',
  },
  {
    busId: 'PUN-SB04',
    routeName: 'Route 4: Baner High Street -> Loyola / St. Vincent Campus',
    driverName: 'Pravin Patil',
    studentsCount: 40,
    studentCount: 40,
    capacity: 50,
    occupancyRate: 80,
    status: 'Direct',
    currentRoute: 'Direct via Pashan link',
    currentDeparture: '06:30 AM',
    currentEta: '06:54 AM (On-Time)',
    recommendedRoute: 'Direct via Pashan link',
    recommendedDeparture: '06:30 AM',
    recommendedEta: '06:54 AM (On-Time)',
    delayAvoidedMin: 0,
    currentCorridor: 'Pashan Arterial',
    recommendedCorridor: 'Pashan Arterial',
  },
  {
    busId: 'PUN-SB05',
    routeName: 'Route 5: Katraj Depot -> Swargate Educational Hub',
    driverName: 'Sanjay More',
    studentsCount: 46,
    studentCount: 46,
    capacity: 50,
    occupancyRate: 92,
    status: 'Rerouted',
    currentRoute: 'Via Pune-Satara Main Road',
    currentDeparture: '06:18 AM',
    currentEta: '07:16 AM (+16m Late)',
    recommendedRoute: 'Via Bibwewadi South Link Road',
    recommendedDeparture: '06:18 AM',
    recommendedEta: '06:56 AM (On-Time)',
    delayAvoidedMin: 16,
    currentCorridor: 'Pune-Satara Road',
    recommendedCorridor: 'Bibwewadi South Link',
  },
  {
    busId: 'PUN-SB06',
    routeName: 'Route 6: Viman Nagar -> Kalyani Nagar / St. Arnold',
    driverName: 'Ganesh Kulkarni',
    studentsCount: 38,
    studentCount: 38,
    capacity: 50,
    occupancyRate: 76,
    status: 'Rerouted',
    currentRoute: 'Via Nagar Main Road',
    currentDeparture: '06:22 AM',
    currentEta: '07:11 AM (+11m Late)',
    recommendedRoute: 'Via Airport South Link Road',
    recommendedDeparture: '06:22 AM',
    recommendedEta: '06:57 AM (On-Time)',
    delayAvoidedMin: 11,
    currentCorridor: 'Nagar Road',
    recommendedCorridor: 'Airport South Link',
  },
  {
    busId: 'PUN-SB07',
    routeName: 'Route 7: Pimpri Station -> Aundh Educational Hub',
    driverName: 'Nitin Gaikwad',
    studentsCount: 45,
    studentCount: 45,
    capacity: 50,
    occupancyRate: 90,
    status: 'Retimed',
    currentRoute: 'Via Old Pune-Mumbai Highway peak cluster',
    currentDeparture: '06:25 AM',
    currentEta: '07:20 AM (+20m Late)',
    recommendedRoute: 'Early Staggered Slot #2',
    recommendedDeparture: '06:10 AM (-15m)',
    recommendedEta: '06:48 AM (On-Time)',
    delayAvoidedMin: 20,
    currentCorridor: 'Old Highway',
    recommendedCorridor: 'Old Highway Staggered Slot',
  },
];

export const PMPML_PUBLIC_ROUTES: PublicTransportRoute[] = [
  {
    id: 'pmpml-100',
    routeId: '100',
    code: '100',
    name: 'Hinjawadi Phase 3 to Pune Railway Station (BRTS)',
    origin: 'Hinjawadi Megapolis Phase 3',
    destination: 'Pune Railway Station Terminal',
    activeBuses: 48,
    delayMin: 7,
    avgDelayMin: 7,
    headwayMin: 4,
    ridershipPerHour: 4600,
    compliancePct: 93,
    crowdLevel: 'High',
    priorityActive: true,
    status: 'On-Time',
    stopsCount: 34,
    passengerLoadPct: 90,
  },
  {
    id: 'pmpml-115',
    routeId: '115-A',
    code: '115-A',
    name: 'Shivaji Nagar to Swargate (via FC Road & Tilak Road)',
    origin: 'Shivaji Nagar Bus Terminal',
    destination: 'Swargate Bus Stand',
    activeBuses: 36,
    delayMin: 11,
    avgDelayMin: 11,
    headwayMin: 5,
    ridershipPerHour: 3800,
    compliancePct: 82,
    crowdLevel: 'Severe',
    priorityActive: true,
    status: 'Slight Delay',
    stopsCount: 22,
    passengerLoadPct: 95,
  },
  {
    id: 'pmpml-204',
    routeId: '204',
    code: '204',
    name: 'Hadapsar Gadital to Katraj (via Kondhwa)',
    origin: 'Hadapsar Gadital Terminal',
    destination: 'Katraj Bus Depot',
    activeBuses: 26,
    delayMin: 5,
    avgDelayMin: 5,
    headwayMin: 8,
    ridershipPerHour: 2100,
    compliancePct: 96,
    crowdLevel: 'Medium',
    priorityActive: true,
    status: 'On-Time',
    stopsCount: 26,
    passengerLoadPct: 78,
  },
  {
    id: 'pmpml-348',
    routeId: '348',
    code: '348',
    name: 'Nigdi Bhakti Shakti to PMC Bhavan',
    origin: 'Nigdi Bus Terminal',
    destination: 'Pune Municipal Corporation (PMC)',
    activeBuses: 32,
    delayMin: 16,
    avgDelayMin: 16,
    headwayMin: 6,
    ridershipPerHour: 3400,
    compliancePct: 68,
    crowdLevel: 'Severe',
    priorityActive: false,
    status: 'Congested',
    stopsCount: 38,
    passengerLoadPct: 98,
  },
  {
    id: 'pmpml-208',
    routeId: '208',
    code: '208',
    name: 'Alandi to Swargate (via Jehangir Chowk & RTO)',
    origin: 'Alandi Bus Terminal',
    destination: 'Swargate Terminal',
    activeBuses: 30,
    delayMin: 6,
    avgDelayMin: 6,
    headwayMin: 6,
    ridershipPerHour: 3200,
    compliancePct: 94,
    crowdLevel: 'High',
    priorityActive: true,
    status: 'On-Time',
    stopsCount: 30,
    passengerLoadPct: 84,
  },
];

export const FREIGHT_SHIFT_LIST: FreightShift[] = [
  {
    id: 'fr-001',
    truckId: 'MH-12-RN-8420',
    company: 'Amazon Logistics Fulfillment (Bhosari / Chakan MIDC)',
    operator: 'Amazon Logistics Hub Pune',
    corridor: 'Chakan MIDC to Hinjawadi IT Expressway',
    vehicleType: 'Heavy Multi-Axle Trucks (32t)',
    tonnage: 32,
    count: 24,
    currentWindow: '07:00 – 08:30 AM (Peak)',
    originalWindow: '07:00 - 08:30 AM',
    recommendedWindow: '05:30 – 06:45 AM (Shifted)',
    status: 'Shifted',
    co2SavedKg: 840,
    co2ReductionKg: 840,
    routeCorridor: 'NH-48 Bypass to Chakan MIDC',
  },
  {
    id: 'fr-002',
    truckId: 'MH-14-CW-2911',
    company: 'Tata Motors Chakan Supply Logistics',
    operator: 'Automotive Freight Linehaul',
    corridor: 'Bhosari to Talegaon Industrial Link',
    vehicleType: 'Medium Commercial Vehicles (14t)',
    tonnage: 14,
    count: 18,
    currentWindow: '07:30 – 09:00 AM (Peak)',
    originalWindow: '07:30 - 09:00 AM',
    recommendedWindow: '10:00 – 11:30 AM (Shifted)',
    status: 'Shifted',
    co2SavedKg: 620,
    co2ReductionKg: 620,
    routeCorridor: 'Spine Road Outer Industrial Link',
  },
  {
    id: 'fr-003',
    truckId: 'MH-12-QZ-9944',
    company: 'Delhivery Surface Express Pune Hub',
    operator: 'Delhivery Surface',
    corridor: 'Pune-Satara Highway (Katraj Tunnel to Wakad)',
    vehicleType: 'Light Commercial Vehicles (Eicher 10.95)',
    tonnage: 10,
    count: 15,
    currentWindow: '07:15 – 08:45 AM (Peak)',
    originalWindow: '07:15 - 08:45 AM',
    recommendedWindow: '06:00 – 07:00 AM (Shifted)',
    status: 'Pending',
    co2SavedKg: 410,
    co2ReductionKg: 410,
    routeCorridor: 'Outer Bypass to Hadapsar',
  },
  {
    id: 'fr-004',
    truckId: 'MH-12-PQ-5520',
    company: 'BlueDart Aviation Surface Hub',
    operator: 'Blue Dart Aviation',
    corridor: 'Pune Nagar Road to Pune Airport Freight Hub',
    vehicleType: 'Medium Goods Vehicles (16t)',
    tonnage: 16,
    count: 12,
    currentWindow: '07:45 – 09:00 AM (Peak)',
    originalWindow: '07:45 - 09:00 AM',
    recommendedWindow: '10:30 – 11:45 AM (Shifted)',
    status: 'Shifted',
    co2SavedKg: 510,
    co2ReductionKg: 510,
    routeCorridor: 'Viman Nagar to Pune Nagar Expressway',
  },
  {
    id: 'fr-005',
    truckId: 'MH-12-EV-7102',
    company: 'Blinkit & Zepto Micro-Fulfillment Pune',
    operator: 'Quick Commerce Fleet',
    corridor: 'Kothrud to Shivaji Nagar Delivery Corridor',
    vehicleType: 'Electric Small Commercial Vehicles',
    tonnage: 4,
    count: 28,
    currentWindow: '07:00 – 08:30 AM (Peak)',
    originalWindow: '07:00 - 08:30 AM',
    recommendedWindow: '05:00 – 06:30 AM (Shifted)',
    status: 'Shifted',
    co2SavedKg: 950,
    co2ReductionKg: 950,
    routeCorridor: 'City Micro-Fulfillment Corridor',
  },
];

export const OPTIMIZATION_PILLARS: OptimizationPillar[] = [
  {
    id: 'pillar-1',
    badge: 'Pillar 1: School Fleet',
    title: 'School Bus Fleet Coordination & Staggering',
    subtitle: '50 Pune school buses staggered and redirected across balanced alternate corridors.',
    impact: '-53% bus delay (saves 14 min per trip)',
    category: 'Fleet Control',
    what: 'Reroute 24 buses via Baner Bypass and stagger departure times by 10-15 minutes.',
    why: 'Prevents 38 buses from simultaneously overloading the narrow Wakad / Hinjawadi bottleneck.',
    details: 'Prevents 38 buses from simultaneously clogging Hinjawadi flyover by shifting 24 buses to Baner bypass and staggering departures by 10-15 minutes.',
    metrics: [
      { label: 'Buses Coordinated', val: '50 Buses' },
      { label: 'Students On-Time', val: '98.4%' },
      { label: 'Hinjawadi Load Shift', val: '-42% PCE' },
    ],
  },
  {
    id: 'pillar-2',
    badge: 'Pillar 2: Freight Curfew',
    title: 'Dynamic Industrial Freight Curfew Windows',
    subtitle: '79 peak commercial freight dispatches shifted into pre-peak (5:30-6:45 AM) and mid-day slots.',
    impact: '-1,850 PCE load during morning peak',
    category: 'Freight Policy',
    what: 'Shift Chakan and Bhosari MIDC logistics trucks into pre-peak (05:30-06:45) and mid-day windows.',
    why: 'Heavy multi-axle freight causes high PCE friction on narrow city commute routes.',
    details: 'Enforces smart slot scheduling with Amazon, Tata Motors, and Delhivery sorting hubs, removing slow-moving heavy commercial vehicles from school commute routes.',
    metrics: [
      { label: 'Trucks Shifted', val: '79 Heavy Trucks' },
      { label: 'CO2 Avoided', val: '3,330 kg/day' },
      { label: 'Peak Capacity Freed', val: '+28%' },
    ],
  },
  {
    id: 'pillar-3',
    badge: 'Pillar 3: PMPML Priority',
    title: 'PMPML Public Transit Priority & Green Waves',
    subtitle: 'Connected signal controllers grant green extensions for 184 active PMPML buses.',
    impact: '+22% passenger throughput along BRTS corridors',
    category: 'Transit Priority',
    what: 'Grant green phase extensions up to 14s for PMPML buses with over 70% passenger occupancy.',
    why: 'Mass public transit moves 86,000 daily Pune commuters and should have intersection priority.',
    details: 'Signal controllers automatically detect approaching PMPML buses with >70% occupancy and extend green phases by up to 14 seconds to clear congestion waves.',
    metrics: [
      { label: 'Buses Given Priority', val: '184 Buses' },
      { label: 'Headway Variance', val: '±1.2 min' },
      { label: 'Daily Commuters Benefited', val: '86,000' },
    ],
  },
  {
    id: 'pillar-4',
    badge: 'Pillar 4: ACO Equilibrium',
    title: 'Ant Colony Optimization Multi-Commodity Equilibrium',
    subtitle: 'ACO routing solver finds global user equilibrium across Pune metropolitan road network.',
    impact: '+46% average corridor speed (13 -> 19 km/h)',
    category: 'ACO Algorithm',
    what: 'Run iterative ACO solver with BPR delay functions across 5 network commodities.',
    why: 'Achieves global network equilibrium rather than selfish uncoordinated shortest-path routing.',
    details: 'Pheromone trail matrix with BPR delay functions iteratively redistributes non-essential private traffic onto high-capacity parallel arterials.',
    metrics: [
      { label: 'Convergence Time', val: '420 ms' },
      { label: 'System Cost Reduction', val: '-34.2%' },
      { label: 'Bottlenecks Cleared', val: '6 of 7' },
    ],
  },
];

export const BEFORE_AFTER_DATA = {
  current: {
    congestionPct: 91,
    busDelayMin: 15,
    averageSpeedKmh: 13,
    totalDelayHours: 8200,
    bottlenecksCount: 7,
    co2EmissionsKg: 14200,
    onTimeArrivalPct: 62,
  },
  optimized: {
    congestionPct: 74,
    busDelayMin: 7,
    averageSpeedKmh: 19,
    totalDelayHours: 3380,
    bottlenecksCount: 1,
    co2EmissionsKg: 11400,
    onTimeArrivalPct: 94,
  },
};
